//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Configuration;

namespace Excel2JsonTool.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [UserScopedSetting()]
        [DefaultSettingValue("")]
        public string LastSelectedExcelFolder
        {
            get
            {
                return ((string)this["LastSelectedExcelFolder"]);
            }
            set
            {
                this["LastSelectedExcelFolder"] = value;
            }
        }

        [UserScopedSetting()]
        [DefaultSettingValue("")]
        public string LastSelectedJsonFolder
        {
            get
            {
                return ((string)this["LastSelectedJsonFolder"]);
            }
            set
            {
                this["LastSelectedJsonFolder"] = value;
            }
        }

    }
}
